print("Hello, World!")
print(5+3)
print("python","is","fun!")
print("She said,\"Hello!\"")
print("First line\ Second line")
print("item1\item2\item3")
print("The result is"42)
print(54678)
print(12.3456)
print("$")
print("apple","banana","cherry",sep=",")
print("Hello,",end="")
print("World!")
print("Python!"*3)
print("\u2764")
print()
print("Hello"+"world!")
print(True)
print(False)
print(1.2e3)
print("""This is a multiline
print statement""")
print("This is a backlash:\\")